services:


  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: deliver
      POSTGRES_USER: deliver
      POSTGRES_PASSWORD: secret
    volumes:
      - deliver-pg-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  deliver-pg-local:
